engines:
  duplication:
    enabled: false
    checks:
      Similar code:
        enabled: false
      UnusedFormalParameter:
        enabled: false
      Controversial/CamelCaseClassName:
        enabled: false
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths: []
- "src/phpFastCache/_extensions/**"
